### ISSUE TITLE
[2023 Others]: 基于 docker 编译安装运行失败

### ISSUE THREAD

**Issue by 0x4A-210** [luooofan/miniob-2023#48]
**base on**: 

**description**: git clone后在docker中运行bahs build.sh init，之后运行bash build.sh编译时docker容器总是CPU占用过高，最后整个docker卡死，后来把build.sh换成
“https://github.com/oceanbase/miniob”
这个仓库里的build.sh，可以编译完成，但是启动./build_debug/bin/observer之后闪退，显示无法初始化线程池和seda stage，应该怎么解决？seda相关的头文件应该从哪里获取？我看源码里很多地方include了这个头文件

**Comment by luooofan** [comment]
没遇到过这些问题

==**==NOTE：本仓库是基于 2023 年 10 月初的 MiniOB 版本进行开发，和官方最新仓库有很多差异==**==

请参考官方文档：
- [如何编译 - MiniOB](https://oceanbase.github.io/miniob/how_to_build.html)
- [使用Docker开发MiniOB - MiniOB](https://oceanbase.github.io/miniob/dev-env/how-to-dev-using-docker.html)

> 可以编译完成，但是启动./build_debug/bin/observer之后闪退，显示无法初始化线程池和seda stage，应该怎么解决？seda相关的头文件应该从哪里获取？我看源码里很多地方include了这个头文件

可以去官方仓库提 issue [New Issue · oceanbase/miniob](https://github.com/oceanbase/miniob/issues/new/choose)
