### ISSUE TITLE
您好，请问update一直报错 poll return POLLHUP=16 or POLLERR=str(event & select.POLLERR)是什么情况？

### ISSUE THREAD

**Issue by asdkfjsd** [luooofan/miniob-2023#51]
问题如图，提交了好多好多次都是这一个情况，我在本地跑测试用例的时候都可以通过。
请问您知道这可能是什么原因吗？谢谢指导

<img width="748" alt="b35fd7ebeb8ffc0162e15975ac8e60e" src="https://github.com/user-attachments/assets/e42bd710-fbcc-4b48-a7c8-632cba56b22d">

**Comment by luooofan** [comment]
应该是 coredump 了，可以试着本地丰富一下测例，然后 Debug、Release 模式都测试下

**Comment by asdkfjsd** [comment]
感谢您的回答，我再测试一下
